[package]
name = "comfybox"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "comfybox"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
console.workspace = true
crossterm.workspace = true
comfybox-core = { path = "../comfybox-core" }
indicatif.workspace = true
reqwest.workspace = true
ratatui.workspace = true
urlencoding.workspace = true
walkdir.workspace = true
inquire.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
